CC=mpic++
EMT_MR: res_emt_mrH.cpp  res_emt_mrH2.cpp res_emt_mrH3.cpp  res_emt_mrH4.cpp
	$(CC) -std=c++11 res_emt_mrH.cpp -o res1_emtMR
	$(CC) -std=c++11 res_emt_mrH2.cpp -o res2_emtMR
	$(CC) -std=c++11 res_emt_mrH3.cpp -o res3_emtMR
	$(CC) -std=c++11 res_emt_mrH4.cpp -o res4_emtMR
